// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"
)

type Trip struct {
	ID        int64     `json:"id"`
	VehicleID int64     `json:"vehicle_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	Mileage   float64   `json:"mileage"`
	AvgSpeed  float64   `json:"avg_speed"`
}

type Vehicle struct {
	ID          int64  `json:"id"`
	PlateNumber string `json:"plate_number"`
	LastStatus  string `json:"last_status"`
}
