version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: postgreslat
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgreslat
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: ./docker
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 8080
      DATABASE_URL: postgres://root:secret@postgres:5432/postgreslat?sslmode=disable
      REDIS_ADDR: redis:6379
      JWT_SECRET: mysecret
      SIMULATOR_VEHICLE_ID: d9c1b442-fb2f-412a-9d2a-a3ab499cd91c
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

volumes:
  pgdata:
