// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Trip struct {
	ID        pgtype.UUID        `json:"id"`
	VehicleID pgtype.UUID        `json:"vehicle_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	Mileage   pgtype.Float8      `json:"mileage"`
	AvgSpeed  pgtype.Float8      `json:"avg_speed"`
}

type Vehicle struct {
	ID          pgtype.UUID `json:"id"`
	PlateNumber string      `json:"plate_number"`
	LastStatus  string      `json:"last_status"`
}
