// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Trip struct {
	ID        uuid.UUID       `json:"id"`
	VehicleID uuid.UUID       `json:"vehicle_id"`
	StartTime time.Time       `json:"start_time"`
	EndTime   sql.NullTime    `json:"end_time"`
	Mileage   sql.NullFloat64 `json:"mileage"`
	AvgSpeed  sql.NullFloat64 `json:"avg_speed"`
}

type Vehicle struct {
	ID          uuid.UUID `json:"id"`
	PlateNumber string    `json:"plate_number"`
	LastStatus  string    `json:"last_status"`
}
