// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: trips.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getTripByID = `-- name: GetTripByID :one
SELECT id, vehicle_id, start_time, end_time, mileage, avg_speed
FROM trips
WHERE id = $1
`

func (q *Queries) GetTripByID(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTripByID, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.StartTime,
		&i.EndTime,
		&i.Mileage,
		&i.AvgSpeed,
	)
	return i, err
}

const getTripsLast24Hours = `-- name: GetTripsLast24Hours :many
SELECT id, vehicle_id, start_time, end_time, mileage, avg_speed
FROM trips
WHERE vehicle_id = $1
  AND start_time >= now() - interval '24 hours'
ORDER BY start_time DESC
`

func (q *Queries) GetTripsLast24Hours(ctx context.Context, vehicleID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, getTripsLast24Hours, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.StartTime,
			&i.EndTime,
			&i.Mileage,
			&i.AvgSpeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrip = `-- name: InsertTrip :exec
INSERT INTO trips (id, vehicle_id, start_time, end_time, mileage, avg_speed)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTripParams struct {
	ID        uuid.UUID       `json:"id"`
	VehicleID uuid.UUID       `json:"vehicle_id"`
	StartTime time.Time       `json:"start_time"`
	EndTime   sql.NullTime    `json:"end_time"`
	Mileage   sql.NullFloat64 `json:"mileage"`
	AvgSpeed  sql.NullFloat64 `json:"avg_speed"`
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) error {
	_, err := q.db.ExecContext(ctx, insertTrip,
		arg.ID,
		arg.VehicleID,
		arg.StartTime,
		arg.EndTime,
		arg.Mileage,
		arg.AvgSpeed,
	)
	return err
}

const listTripsByVehicle = `-- name: ListTripsByVehicle :many
SELECT id, vehicle_id, start_time, end_time, mileage, avg_speed
FROM trips
WHERE vehicle_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListTripsByVehicleParams struct {
	VehicleID uuid.UUID `json:"vehicle_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListTripsByVehicle(ctx context.Context, arg ListTripsByVehicleParams) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTripsByVehicle, arg.VehicleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.StartTime,
			&i.EndTime,
			&i.Mileage,
			&i.AvgSpeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
